### ISSUE TITLE
org.apache.tomcat.util.bcel.classfile.ClassFormatException:Invalid byte tag in constant pool: 19

### ISSUE THREAD

**Issue by ZCHWorld** [aspose-words/Aspose.Words-for-Java#54]
my app deploy in Tomcat8.5.2 and jdk1.8.And I through Maven dependency aspose-words-19.6-jdk17.jar.
when i startup tomcat,it throw Exception:

```
08-Jul-2019 08:40:01.372 SEVERE [localhost-startStop-1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [META-INF/versions/9/module-info.class] from Jar [file:/D:/apache-tomcat-8.5.2/webapps/ROOT/WEB-INF/lib/aspose-words-19.6-jdk17.jar] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
         at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
         at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54)
         at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:174)
         at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)
         at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2042)
         at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1989)
         at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1959)
         at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1912)
         at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1154)
         at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771)
         at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:298)
         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5093)
         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1405)
         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1395)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
```

**Comment by awaishafeez** [comment]
@ZCHWorld,

This does not seem to be a bug in Aspose.Words for Java. Instead, it seems to be an issue with Tomcat. Please check the following links:
https://bz.apache.org/bugzilla/show_bug.cgi?id=60688
https://stackoverflow.com/questions/23541532/org-apache-tomcat-util-bcel-classfile-classformatexception-invalid-byte-tag-in

To fix it, please try to update Tomcat to the latest version and also maybe delete the annotation scan. Hope, this helps.

**Comment by ZCHWorld** [comment]
Thanks to awaishafeez's answer, I finally decided to use Tomcat 9 and turn off the TLD scan.

**Comment by jcabrerazuniga** [comment]
How to turn off the TLD scan ?

**Comment by ZCHWorld** [comment]
> How to turn off the TLD scan ?

edit **apache-tomcat-9.0.22\conf\catalina.properties** file:
`tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*`
